<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Setting::create([

            'name' => 'Urban Areas Development Authority',
            'email' => 'ask@abc.com',
             'phone_no' => '000000000',
            'address' => 'Kanju Township Swat',
            'sub_charges' => 10,
            'invoice_prefix' => 'UADA-',
            'receipt_footer' => 'Bill generated by UADA',
            'dept_logo' => '',
            'govt_logo' => '',
        ]);
    }
}
